changelog:
  exclude:
    labels:
      - release
  categories:
    - title: aeico-view
      labels: ['aeico-view']
    - title: aeico-element
      labels: ['aeico-element']
    - title: aeico-localize
      labels: ['aeico-localize']
    - title: aeico-ssr
      labels: ['aeico-ssr']
    - title: aeico-signals
      labels: ['aeico-signals']
    - title: aeico
      labels: ['aeico']
    - title: Other Changes
      labels: ['*']
